// flow-typed signature: e83cfa15fc92db4f0f41038e9b327516
// flow-typed version: <<STUB>>/react-redux-toastr_v^6.2.6/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-redux-toastr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-redux-toastr' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-redux-toastr/lib/actions' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/Button' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/config' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/constants' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/Icon' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/icons' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/index' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/ReduxToastr' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/ToastrBox' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/ToastrConfirm' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/toastrEmitter' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/lib/utils' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/actions' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/Button' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/config' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/constants' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/Icon' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/icons' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/index' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/ProgressBar' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/reducer' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/ReduxToastr' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/ToastrBox' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/ToastrConfirm' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/toastrEmitter' {
  declare module.exports: any;
}

declare module 'react-redux-toastr/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-redux-toastr/lib/actions.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/actions'>;
}
declare module 'react-redux-toastr/lib/Button.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/Button'>;
}
declare module 'react-redux-toastr/lib/config.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/config'>;
}
declare module 'react-redux-toastr/lib/constants.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/constants'>;
}
declare module 'react-redux-toastr/lib/Icon.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/Icon'>;
}
declare module 'react-redux-toastr/lib/icons.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/icons'>;
}
declare module 'react-redux-toastr/lib/index.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/index'>;
}
declare module 'react-redux-toastr/lib/ProgressBar.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/ProgressBar'>;
}
declare module 'react-redux-toastr/lib/reducer.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/reducer'>;
}
declare module 'react-redux-toastr/lib/ReduxToastr.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/ReduxToastr'>;
}
declare module 'react-redux-toastr/lib/ToastrBox.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/ToastrBox'>;
}
declare module 'react-redux-toastr/lib/ToastrConfirm.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/ToastrConfirm'>;
}
declare module 'react-redux-toastr/lib/toastrEmitter.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/toastrEmitter'>;
}
declare module 'react-redux-toastr/lib/utils.js' {
  declare module.exports: $Exports<'react-redux-toastr/lib/utils'>;
}
declare module 'react-redux-toastr/src/actions.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/actions'>;
}
declare module 'react-redux-toastr/src/Button.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/Button'>;
}
declare module 'react-redux-toastr/src/config.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/config'>;
}
declare module 'react-redux-toastr/src/constants.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/constants'>;
}
declare module 'react-redux-toastr/src/Icon.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/Icon'>;
}
declare module 'react-redux-toastr/src/icons.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/icons'>;
}
declare module 'react-redux-toastr/src/index.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/index'>;
}
declare module 'react-redux-toastr/src/ProgressBar.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/ProgressBar'>;
}
declare module 'react-redux-toastr/src/reducer.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/reducer'>;
}
declare module 'react-redux-toastr/src/ReduxToastr.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/ReduxToastr'>;
}
declare module 'react-redux-toastr/src/ToastrBox.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/ToastrBox'>;
}
declare module 'react-redux-toastr/src/ToastrConfirm.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/ToastrConfirm'>;
}
declare module 'react-redux-toastr/src/toastrEmitter.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/toastrEmitter'>;
}
declare module 'react-redux-toastr/src/utils.js' {
  declare module.exports: $Exports<'react-redux-toastr/src/utils'>;
}
