// flow-typed signature: 6414ab8df68b81c73b6ef893c75804c4
// flow-typed version: <<STUB>>/redux-saga-router_v^2.1.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-saga-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-saga-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-saga-router/lib/buildRouteMatcher' {
  declare module.exports: any;
}

declare module 'redux-saga-router/lib/createHistoryChannel' {
  declare module.exports: any;
}

declare module 'redux-saga-router/lib/createRouter' {
  declare module.exports: any;
}

declare module 'redux-saga-router/lib/index' {
  declare module.exports: any;
}

declare module 'redux-saga-router/lib/oldRouter' {
  declare module.exports: any;
}

declare module 'redux-saga-router/lib/react/createLink' {
  declare module.exports: any;
}

declare module 'redux-saga-router/lib/router' {
  declare module.exports: any;
}

declare module 'redux-saga-router/react' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/buildRouteMatcher' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/createHistoryChannel' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/createRouter' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/index' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/oldRouter' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/react/createLink' {
  declare module.exports: any;
}

declare module 'redux-saga-router/src/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-saga-router/lib/buildRouteMatcher.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/buildRouteMatcher'>;
}
declare module 'redux-saga-router/lib/createHistoryChannel.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/createHistoryChannel'>;
}
declare module 'redux-saga-router/lib/createRouter.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/createRouter'>;
}
declare module 'redux-saga-router/lib/index.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/index'>;
}
declare module 'redux-saga-router/lib/oldRouter.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/oldRouter'>;
}
declare module 'redux-saga-router/lib/react/createLink.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/react/createLink'>;
}
declare module 'redux-saga-router/lib/router.js' {
  declare module.exports: $Exports<'redux-saga-router/lib/router'>;
}
declare module 'redux-saga-router/react.js' {
  declare module.exports: $Exports<'redux-saga-router/react'>;
}
declare module 'redux-saga-router/src/buildRouteMatcher.js' {
  declare module.exports: $Exports<'redux-saga-router/src/buildRouteMatcher'>;
}
declare module 'redux-saga-router/src/createHistoryChannel.js' {
  declare module.exports: $Exports<'redux-saga-router/src/createHistoryChannel'>;
}
declare module 'redux-saga-router/src/createRouter.js' {
  declare module.exports: $Exports<'redux-saga-router/src/createRouter'>;
}
declare module 'redux-saga-router/src/index.js' {
  declare module.exports: $Exports<'redux-saga-router/src/index'>;
}
declare module 'redux-saga-router/src/oldRouter.js' {
  declare module.exports: $Exports<'redux-saga-router/src/oldRouter'>;
}
declare module 'redux-saga-router/src/react/createLink.js' {
  declare module.exports: $Exports<'redux-saga-router/src/react/createLink'>;
}
declare module 'redux-saga-router/src/router.js' {
  declare module.exports: $Exports<'redux-saga-router/src/router'>;
}
