// flow-typed signature: c4c370b7c1049cffa6a4151f9585668c
// flow-typed version: <<STUB>>/redux-seamless-immutable_v^0.3.0/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-seamless-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-seamless-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-seamless-immutable/lib/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/lib/index' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/lib/routerReducer' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/lib/stateTransformer' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/src/combineReducers' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/src/index' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/src/routerReducer' {
  declare module.exports: any;
}

declare module 'redux-seamless-immutable/src/stateTransformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-seamless-immutable/lib/combineReducers.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/lib/combineReducers'>;
}
declare module 'redux-seamless-immutable/lib/index.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/lib/index'>;
}
declare module 'redux-seamless-immutable/lib/routerReducer.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/lib/routerReducer'>;
}
declare module 'redux-seamless-immutable/lib/stateTransformer.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/lib/stateTransformer'>;
}
declare module 'redux-seamless-immutable/src/combineReducers.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/src/combineReducers'>;
}
declare module 'redux-seamless-immutable/src/index.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/src/index'>;
}
declare module 'redux-seamless-immutable/src/routerReducer.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/src/routerReducer'>;
}
declare module 'redux-seamless-immutable/src/stateTransformer.js' {
  declare module.exports: $Exports<'redux-seamless-immutable/src/stateTransformer'>;
}
