// flow-typed signature: 67976f2ba69eef934dde8c0ba365332c
// flow-typed version: <<STUB>>/sockjs-client_v^1.1.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sockjs-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sockjs-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sockjs-client/dist/sockjs' {
  declare module.exports: any;
}

declare module 'sockjs-client/dist/sockjs.min' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/entry' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/event/close' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/event/emitter' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/event/event' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/event/eventtarget' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/event/trans-message' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/facade' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/iframe-bootstrap' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/info-ajax' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/info-iframe-receiver' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/info-iframe' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/info-receiver' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/location' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/main' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/shims' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport-list' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/browser/abstract-xhr' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/browser/eventsource' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/browser/websocket' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/driver/websocket' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/driver/xhr' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/eventsource' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/htmlfile' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/iframe' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/jsonp-polling' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/lib/ajax-based' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/lib/buffered-sender' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/lib/iframe-wrap' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/lib/polling' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/lib/sender-receiver' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/receiver/eventsource' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/receiver/htmlfile' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/receiver/jsonp' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/receiver/xhr' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/sender/jsonp' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/sender/xdr' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/sender/xhr-cors' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/sender/xhr-fake' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/sender/xhr-local' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/websocket' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/xdr-polling' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/xdr-streaming' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/xhr-polling' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/transport/xhr-streaming' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/browser-crypto' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/browser' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/escape' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/event' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/iframe' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/log' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/object' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/random' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/transport' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/utils/url' {
  declare module.exports: any;
}

declare module 'sockjs-client/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sockjs-client/dist/sockjs.js' {
  declare module.exports: $Exports<'sockjs-client/dist/sockjs'>;
}
declare module 'sockjs-client/dist/sockjs.min.js' {
  declare module.exports: $Exports<'sockjs-client/dist/sockjs.min'>;
}
declare module 'sockjs-client/lib/entry.js' {
  declare module.exports: $Exports<'sockjs-client/lib/entry'>;
}
declare module 'sockjs-client/lib/event/close.js' {
  declare module.exports: $Exports<'sockjs-client/lib/event/close'>;
}
declare module 'sockjs-client/lib/event/emitter.js' {
  declare module.exports: $Exports<'sockjs-client/lib/event/emitter'>;
}
declare module 'sockjs-client/lib/event/event.js' {
  declare module.exports: $Exports<'sockjs-client/lib/event/event'>;
}
declare module 'sockjs-client/lib/event/eventtarget.js' {
  declare module.exports: $Exports<'sockjs-client/lib/event/eventtarget'>;
}
declare module 'sockjs-client/lib/event/trans-message.js' {
  declare module.exports: $Exports<'sockjs-client/lib/event/trans-message'>;
}
declare module 'sockjs-client/lib/facade.js' {
  declare module.exports: $Exports<'sockjs-client/lib/facade'>;
}
declare module 'sockjs-client/lib/iframe-bootstrap.js' {
  declare module.exports: $Exports<'sockjs-client/lib/iframe-bootstrap'>;
}
declare module 'sockjs-client/lib/info-ajax.js' {
  declare module.exports: $Exports<'sockjs-client/lib/info-ajax'>;
}
declare module 'sockjs-client/lib/info-iframe-receiver.js' {
  declare module.exports: $Exports<'sockjs-client/lib/info-iframe-receiver'>;
}
declare module 'sockjs-client/lib/info-iframe.js' {
  declare module.exports: $Exports<'sockjs-client/lib/info-iframe'>;
}
declare module 'sockjs-client/lib/info-receiver.js' {
  declare module.exports: $Exports<'sockjs-client/lib/info-receiver'>;
}
declare module 'sockjs-client/lib/location.js' {
  declare module.exports: $Exports<'sockjs-client/lib/location'>;
}
declare module 'sockjs-client/lib/main.js' {
  declare module.exports: $Exports<'sockjs-client/lib/main'>;
}
declare module 'sockjs-client/lib/shims.js' {
  declare module.exports: $Exports<'sockjs-client/lib/shims'>;
}
declare module 'sockjs-client/lib/transport-list.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport-list'>;
}
declare module 'sockjs-client/lib/transport/browser/abstract-xhr.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/browser/abstract-xhr'>;
}
declare module 'sockjs-client/lib/transport/browser/eventsource.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/browser/eventsource'>;
}
declare module 'sockjs-client/lib/transport/browser/websocket.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/browser/websocket'>;
}
declare module 'sockjs-client/lib/transport/driver/websocket.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/driver/websocket'>;
}
declare module 'sockjs-client/lib/transport/driver/xhr.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/driver/xhr'>;
}
declare module 'sockjs-client/lib/transport/eventsource.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/eventsource'>;
}
declare module 'sockjs-client/lib/transport/htmlfile.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/htmlfile'>;
}
declare module 'sockjs-client/lib/transport/iframe.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/iframe'>;
}
declare module 'sockjs-client/lib/transport/jsonp-polling.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/jsonp-polling'>;
}
declare module 'sockjs-client/lib/transport/lib/ajax-based.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/lib/ajax-based'>;
}
declare module 'sockjs-client/lib/transport/lib/buffered-sender.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/lib/buffered-sender'>;
}
declare module 'sockjs-client/lib/transport/lib/iframe-wrap.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/lib/iframe-wrap'>;
}
declare module 'sockjs-client/lib/transport/lib/polling.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/lib/polling'>;
}
declare module 'sockjs-client/lib/transport/lib/sender-receiver.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/lib/sender-receiver'>;
}
declare module 'sockjs-client/lib/transport/receiver/eventsource.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/receiver/eventsource'>;
}
declare module 'sockjs-client/lib/transport/receiver/htmlfile.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/receiver/htmlfile'>;
}
declare module 'sockjs-client/lib/transport/receiver/jsonp.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/receiver/jsonp'>;
}
declare module 'sockjs-client/lib/transport/receiver/xhr.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/receiver/xhr'>;
}
declare module 'sockjs-client/lib/transport/sender/jsonp.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/sender/jsonp'>;
}
declare module 'sockjs-client/lib/transport/sender/xdr.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/sender/xdr'>;
}
declare module 'sockjs-client/lib/transport/sender/xhr-cors.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/sender/xhr-cors'>;
}
declare module 'sockjs-client/lib/transport/sender/xhr-fake.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/sender/xhr-fake'>;
}
declare module 'sockjs-client/lib/transport/sender/xhr-local.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/sender/xhr-local'>;
}
declare module 'sockjs-client/lib/transport/websocket.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/websocket'>;
}
declare module 'sockjs-client/lib/transport/xdr-polling.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/xdr-polling'>;
}
declare module 'sockjs-client/lib/transport/xdr-streaming.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/xdr-streaming'>;
}
declare module 'sockjs-client/lib/transport/xhr-polling.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/xhr-polling'>;
}
declare module 'sockjs-client/lib/transport/xhr-streaming.js' {
  declare module.exports: $Exports<'sockjs-client/lib/transport/xhr-streaming'>;
}
declare module 'sockjs-client/lib/utils/browser-crypto.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/browser-crypto'>;
}
declare module 'sockjs-client/lib/utils/browser.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/browser'>;
}
declare module 'sockjs-client/lib/utils/escape.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/escape'>;
}
declare module 'sockjs-client/lib/utils/event.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/event'>;
}
declare module 'sockjs-client/lib/utils/iframe.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/iframe'>;
}
declare module 'sockjs-client/lib/utils/log.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/log'>;
}
declare module 'sockjs-client/lib/utils/object.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/object'>;
}
declare module 'sockjs-client/lib/utils/random.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/random'>;
}
declare module 'sockjs-client/lib/utils/transport.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/transport'>;
}
declare module 'sockjs-client/lib/utils/url.js' {
  declare module.exports: $Exports<'sockjs-client/lib/utils/url'>;
}
declare module 'sockjs-client/lib/version.js' {
  declare module.exports: $Exports<'sockjs-client/lib/version'>;
}
