// flow-typed signature: d776c429ba6acfd6ff5187bd78efb074
// flow-typed version: <<STUB>>/webstomp-client_v^1.0.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webstomp-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webstomp-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webstomp-client/dist/webstomp' {
  declare module.exports: any;
}

declare module 'webstomp-client/dist/webstomp.min' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/client' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/frame' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/utils' {
  declare module.exports: any;
}

declare module 'webstomp-client/src/webstomp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webstomp-client/dist/webstomp.js' {
  declare module.exports: $Exports<'webstomp-client/dist/webstomp'>;
}
declare module 'webstomp-client/dist/webstomp.min.js' {
  declare module.exports: $Exports<'webstomp-client/dist/webstomp.min'>;
}
declare module 'webstomp-client/src/client.js' {
  declare module.exports: $Exports<'webstomp-client/src/client'>;
}
declare module 'webstomp-client/src/frame.js' {
  declare module.exports: $Exports<'webstomp-client/src/frame'>;
}
declare module 'webstomp-client/src/utils.js' {
  declare module.exports: $Exports<'webstomp-client/src/utils'>;
}
declare module 'webstomp-client/src/webstomp.js' {
  declare module.exports: $Exports<'webstomp-client/src/webstomp'>;
}
